/*

LICENSE

*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1"
	scheme "github.com/portworx/kdmp/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VolumeBackupsGetter has a method to return a VolumeBackupInterface.
// A group's client should implement this interface.
type VolumeBackupsGetter interface {
	VolumeBackups(namespace string) VolumeBackupInterface
}

// VolumeBackupInterface has methods to work with VolumeBackup resources.
type VolumeBackupInterface interface {
	Create(*v1alpha1.VolumeBackup) (*v1alpha1.VolumeBackup, error)
	Update(*v1alpha1.VolumeBackup) (*v1alpha1.VolumeBackup, error)
	UpdateStatus(*v1alpha1.VolumeBackup) (*v1alpha1.VolumeBackup, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.VolumeBackup, error)
	List(opts v1.ListOptions) (*v1alpha1.VolumeBackupList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VolumeBackup, err error)
	VolumeBackupExpansion
}

// volumeBackups implements VolumeBackupInterface
type volumeBackups struct {
	client rest.Interface
	ns     string
}

// newVolumeBackups returns a VolumeBackups
func newVolumeBackups(c *KdmpV1alpha1Client, namespace string) *volumeBackups {
	return &volumeBackups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the volumeBackup, and returns the corresponding volumeBackup object, and an error if there is any.
func (c *volumeBackups) Get(name string, options v1.GetOptions) (result *v1alpha1.VolumeBackup, err error) {
	result = &v1alpha1.VolumeBackup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("volumebackups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VolumeBackups that match those selectors.
func (c *volumeBackups) List(opts v1.ListOptions) (result *v1alpha1.VolumeBackupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VolumeBackupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("volumebackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested volumeBackups.
func (c *volumeBackups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("volumebackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a volumeBackup and creates it.  Returns the server's representation of the volumeBackup, and an error, if there is any.
func (c *volumeBackups) Create(volumeBackup *v1alpha1.VolumeBackup) (result *v1alpha1.VolumeBackup, err error) {
	result = &v1alpha1.VolumeBackup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("volumebackups").
		Body(volumeBackup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a volumeBackup and updates it. Returns the server's representation of the volumeBackup, and an error, if there is any.
func (c *volumeBackups) Update(volumeBackup *v1alpha1.VolumeBackup) (result *v1alpha1.VolumeBackup, err error) {
	result = &v1alpha1.VolumeBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("volumebackups").
		Name(volumeBackup.Name).
		Body(volumeBackup).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *volumeBackups) UpdateStatus(volumeBackup *v1alpha1.VolumeBackup) (result *v1alpha1.VolumeBackup, err error) {
	result = &v1alpha1.VolumeBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("volumebackups").
		Name(volumeBackup.Name).
		SubResource("status").
		Body(volumeBackup).
		Do().
		Into(result)
	return
}

// Delete takes name of the volumeBackup and deletes it. Returns an error if one occurs.
func (c *volumeBackups) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("volumebackups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *volumeBackups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("volumebackups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched volumeBackup.
func (c *volumeBackups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VolumeBackup, err error) {
	result = &v1alpha1.VolumeBackup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("volumebackups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
