FROM registry.access.redhat.com/ubi9-minimal:latest

MAINTAINER Portworx Inc. <support@portworx.com>

RUN microdnf install -y bash vim make wget gpg ca-certificates yum && \
        microdnf clean all

WORKDIR /

COPY ./bin/nfsexecutor /

ENTRYPOINT ["/nfsexecutor"] 