FROM registry.access.redhat.com/ubi8-minimal:latest

MAINTAINER Portworx Inc. <support@portworx.com>

RUN microdnf install bash curl vim make wget gpg ca-certificates yum && \
        microdnf clean all

RUN rpm --import https://kopia.io/signing-key

COPY kopia.repo /etc/yum.repos.d/kopia.repo

RUN yum install -y kopia-0.10.6
WORKDIR /

COPY ./bin/kopiaexecutor /

ENTRYPOINT ["/kopiaexecutor"] 