FROM registry.access.redhat.com/ubi8-minimal:latest

MAINTAINER Portworx Inc. <support@portworx.com>

RUN microdnf install bash curl vim make wget gpg ca-certificates yum && \
        microdnf clean all

WORKDIR /

COPY ./bin/nfsexecutor /

ENTRYPOINT ["/nfsexecutor"] 