FROM restic/restic:latest AS restic

FROM ubuntu:22.04
MAINTAINER Portworx Inc. <support@portworx.com>

RUN apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
    && apt-get clean -y \
    && apt-get autoremove -y \
    && rm -rf /tmp/* /var/tmp/* \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY --from=restic /usr/bin/restic /usr/bin
COPY ./bin/resticexecutor /

ENTRYPOINT ["/resticexecutor"]
