FROM registry.access.redhat.com/ubi9-minimal:latest

MAINTAINER Portworx Inc. <support@portworx.com>

RUN microdnf install -y bash vim make wget gpg ca-certificates yum && \
        microdnf clean all

RUN curl -LJO https://github.com/kopia/kopia/releases/download/v0.14.1/kopia-0.14.1.x86_64.rpm

RUN yum install -y kopia-0.14.1.x86_64.rpm

WORKDIR /

COPY ./bin/kopiaexecutor /

ENTRYPOINT ["/kopiaexecutor"] 