FROM restic/restic:latest AS restic

FROM ubuntu
MAINTAINER Portworx Inc. <support@portworx.com>

WORKDIR /

COPY --from=restic /usr/bin/restic /usr/bin
COPY ./bin/resticexecutor /

ENTRYPOINT ["/resticexecutor"]
