/*

LICENSE

*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/portworx/kdmp/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BackupLocationMaintenances returns a BackupLocationMaintenanceInformer.
	BackupLocationMaintenances() BackupLocationMaintenanceInformer
	// DataExports returns a DataExportInformer.
	DataExports() DataExportInformer
	// VolumeBackups returns a VolumeBackupInformer.
	VolumeBackups() VolumeBackupInformer
	// VolumeBackupDeletes returns a VolumeBackupDeleteInformer.
	VolumeBackupDeletes() VolumeBackupDeleteInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// BackupLocationMaintenances returns a BackupLocationMaintenanceInformer.
func (v *version) BackupLocationMaintenances() BackupLocationMaintenanceInformer {
	return &backupLocationMaintenanceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DataExports returns a DataExportInformer.
func (v *version) DataExports() DataExportInformer {
	return &dataExportInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VolumeBackups returns a VolumeBackupInformer.
func (v *version) VolumeBackups() VolumeBackupInformer {
	return &volumeBackupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VolumeBackupDeletes returns a VolumeBackupDeleteInformer.
func (v *version) VolumeBackupDeletes() VolumeBackupDeleteInformer {
	return &volumeBackupDeleteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
