/*

LICENSE

*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	kdmpv1alpha1 "github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1"
	versioned "github.com/portworx/kdmp/pkg/client/clientset/versioned"
	internalinterfaces "github.com/portworx/kdmp/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/portworx/kdmp/pkg/client/listers/kdmp/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VolumeBackupDeleteInformer provides access to a shared informer and lister for
// VolumeBackupDeletes.
type VolumeBackupDeleteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VolumeBackupDeleteLister
}

type volumeBackupDeleteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVolumeBackupDeleteInformer constructs a new informer for VolumeBackupDelete type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVolumeBackupDeleteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVolumeBackupDeleteInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVolumeBackupDeleteInformer constructs a new informer for VolumeBackupDelete type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVolumeBackupDeleteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KdmpV1alpha1().VolumeBackupDeletes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KdmpV1alpha1().VolumeBackupDeletes(namespace).Watch(context.TODO(), options)
			},
		},
		&kdmpv1alpha1.VolumeBackupDelete{},
		resyncPeriod,
		indexers,
	)
}

func (f *volumeBackupDeleteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVolumeBackupDeleteInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *volumeBackupDeleteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kdmpv1alpha1.VolumeBackupDelete{}, f.defaultInformer)
}

func (f *volumeBackupDeleteInformer) Lister() v1alpha1.VolumeBackupDeleteLister {
	return v1alpha1.NewVolumeBackupDeleteLister(f.Informer().GetIndexer())
}
