/*

LICENSE

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupLocationMaintenances implements BackupLocationMaintenanceInterface
type FakeBackupLocationMaintenances struct {
	Fake *FakeKdmpV1alpha1
	ns   string
}

var backuplocationmaintenancesResource = schema.GroupVersionResource{Group: "kdmp.portworx.com", Version: "v1alpha1", Resource: "backuplocationmaintenances"}

var backuplocationmaintenancesKind = schema.GroupVersionKind{Group: "kdmp.portworx.com", Version: "v1alpha1", Kind: "BackupLocationMaintenance"}

// Get takes name of the backupLocationMaintenance, and returns the corresponding backupLocationMaintenance object, and an error if there is any.
func (c *FakeBackupLocationMaintenances) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BackupLocationMaintenance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backuplocationmaintenancesResource, c.ns, name), &v1alpha1.BackupLocationMaintenance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupLocationMaintenance), err
}

// List takes label and field selectors, and returns the list of BackupLocationMaintenances that match those selectors.
func (c *FakeBackupLocationMaintenances) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BackupLocationMaintenanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backuplocationmaintenancesResource, backuplocationmaintenancesKind, c.ns, opts), &v1alpha1.BackupLocationMaintenanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BackupLocationMaintenanceList{ListMeta: obj.(*v1alpha1.BackupLocationMaintenanceList).ListMeta}
	for _, item := range obj.(*v1alpha1.BackupLocationMaintenanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupLocationMaintenances.
func (c *FakeBackupLocationMaintenances) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backuplocationmaintenancesResource, c.ns, opts))

}

// Create takes the representation of a backupLocationMaintenance and creates it.  Returns the server's representation of the backupLocationMaintenance, and an error, if there is any.
func (c *FakeBackupLocationMaintenances) Create(ctx context.Context, backupLocationMaintenance *v1alpha1.BackupLocationMaintenance, opts v1.CreateOptions) (result *v1alpha1.BackupLocationMaintenance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backuplocationmaintenancesResource, c.ns, backupLocationMaintenance), &v1alpha1.BackupLocationMaintenance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupLocationMaintenance), err
}

// Update takes the representation of a backupLocationMaintenance and updates it. Returns the server's representation of the backupLocationMaintenance, and an error, if there is any.
func (c *FakeBackupLocationMaintenances) Update(ctx context.Context, backupLocationMaintenance *v1alpha1.BackupLocationMaintenance, opts v1.UpdateOptions) (result *v1alpha1.BackupLocationMaintenance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backuplocationmaintenancesResource, c.ns, backupLocationMaintenance), &v1alpha1.BackupLocationMaintenance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupLocationMaintenance), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackupLocationMaintenances) UpdateStatus(ctx context.Context, backupLocationMaintenance *v1alpha1.BackupLocationMaintenance, opts v1.UpdateOptions) (*v1alpha1.BackupLocationMaintenance, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(backuplocationmaintenancesResource, "status", c.ns, backupLocationMaintenance), &v1alpha1.BackupLocationMaintenance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupLocationMaintenance), err
}

// Delete takes name of the backupLocationMaintenance and deletes it. Returns an error if one occurs.
func (c *FakeBackupLocationMaintenances) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(backuplocationmaintenancesResource, c.ns, name, opts), &v1alpha1.BackupLocationMaintenance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupLocationMaintenances) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backuplocationmaintenancesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BackupLocationMaintenanceList{})
	return err
}

// Patch applies the patch and returns the patched backupLocationMaintenance.
func (c *FakeBackupLocationMaintenances) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BackupLocationMaintenance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backuplocationmaintenancesResource, c.ns, name, pt, data, subresources...), &v1alpha1.BackupLocationMaintenance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupLocationMaintenance), err
}
