/*

LICENSE

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKdmpV1alpha1 struct {
	*testing.Fake
}

func (c *FakeKdmpV1alpha1) DataExports(namespace string) v1alpha1.DataExportInterface {
	return &FakeDataExports{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKdmpV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
