/*

LICENSE

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourceBackups implements ResourceBackupInterface
type FakeResourceBackups struct {
	Fake *FakeKdmpV1alpha1
	ns   string
}

var resourcebackupsResource = schema.GroupVersionResource{Group: "kdmp.portworx.com", Version: "v1alpha1", Resource: "resourcebackups"}

var resourcebackupsKind = schema.GroupVersionKind{Group: "kdmp.portworx.com", Version: "v1alpha1", Kind: "ResourceBackup"}

// Get takes name of the resourceBackup, and returns the corresponding resourceBackup object, and an error if there is any.
func (c *FakeResourceBackups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ResourceBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourcebackupsResource, c.ns, name), &v1alpha1.ResourceBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceBackup), err
}

// List takes label and field selectors, and returns the list of ResourceBackups that match those selectors.
func (c *FakeResourceBackups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ResourceBackupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourcebackupsResource, resourcebackupsKind, c.ns, opts), &v1alpha1.ResourceBackupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ResourceBackupList{ListMeta: obj.(*v1alpha1.ResourceBackupList).ListMeta}
	for _, item := range obj.(*v1alpha1.ResourceBackupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourceBackups.
func (c *FakeResourceBackups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourcebackupsResource, c.ns, opts))

}

// Create takes the representation of a resourceBackup and creates it.  Returns the server's representation of the resourceBackup, and an error, if there is any.
func (c *FakeResourceBackups) Create(ctx context.Context, resourceBackup *v1alpha1.ResourceBackup, opts v1.CreateOptions) (result *v1alpha1.ResourceBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourcebackupsResource, c.ns, resourceBackup), &v1alpha1.ResourceBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceBackup), err
}

// Update takes the representation of a resourceBackup and updates it. Returns the server's representation of the resourceBackup, and an error, if there is any.
func (c *FakeResourceBackups) Update(ctx context.Context, resourceBackup *v1alpha1.ResourceBackup, opts v1.UpdateOptions) (result *v1alpha1.ResourceBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourcebackupsResource, c.ns, resourceBackup), &v1alpha1.ResourceBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceBackup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeResourceBackups) UpdateStatus(ctx context.Context, resourceBackup *v1alpha1.ResourceBackup, opts v1.UpdateOptions) (*v1alpha1.ResourceBackup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(resourcebackupsResource, "status", c.ns, resourceBackup), &v1alpha1.ResourceBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceBackup), err
}

// Delete takes name of the resourceBackup and deletes it. Returns an error if one occurs.
func (c *FakeResourceBackups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(resourcebackupsResource, c.ns, name), &v1alpha1.ResourceBackup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourceBackups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourcebackupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ResourceBackupList{})
	return err
}

// Patch applies the patch and returns the patched resourceBackup.
func (c *FakeResourceBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ResourceBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourcebackupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ResourceBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceBackup), err
}
