/*

LICENSE

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumeBackupDeletes implements VolumeBackupDeleteInterface
type FakeVolumeBackupDeletes struct {
	Fake *FakeKdmpV1alpha1
	ns   string
}

var volumebackupdeletesResource = schema.GroupVersionResource{Group: "kdmp.portworx.com", Version: "v1alpha1", Resource: "volumebackupdeletes"}

var volumebackupdeletesKind = schema.GroupVersionKind{Group: "kdmp.portworx.com", Version: "v1alpha1", Kind: "VolumeBackupDelete"}

// Get takes name of the volumeBackupDelete, and returns the corresponding volumeBackupDelete object, and an error if there is any.
func (c *FakeVolumeBackupDeletes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VolumeBackupDelete, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(volumebackupdeletesResource, c.ns, name), &v1alpha1.VolumeBackupDelete{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeBackupDelete), err
}

// List takes label and field selectors, and returns the list of VolumeBackupDeletes that match those selectors.
func (c *FakeVolumeBackupDeletes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VolumeBackupDeleteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(volumebackupdeletesResource, volumebackupdeletesKind, c.ns, opts), &v1alpha1.VolumeBackupDeleteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VolumeBackupDeleteList{ListMeta: obj.(*v1alpha1.VolumeBackupDeleteList).ListMeta}
	for _, item := range obj.(*v1alpha1.VolumeBackupDeleteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumeBackupDeletes.
func (c *FakeVolumeBackupDeletes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(volumebackupdeletesResource, c.ns, opts))

}

// Create takes the representation of a volumeBackupDelete and creates it.  Returns the server's representation of the volumeBackupDelete, and an error, if there is any.
func (c *FakeVolumeBackupDeletes) Create(ctx context.Context, volumeBackupDelete *v1alpha1.VolumeBackupDelete, opts v1.CreateOptions) (result *v1alpha1.VolumeBackupDelete, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(volumebackupdeletesResource, c.ns, volumeBackupDelete), &v1alpha1.VolumeBackupDelete{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeBackupDelete), err
}

// Update takes the representation of a volumeBackupDelete and updates it. Returns the server's representation of the volumeBackupDelete, and an error, if there is any.
func (c *FakeVolumeBackupDeletes) Update(ctx context.Context, volumeBackupDelete *v1alpha1.VolumeBackupDelete, opts v1.UpdateOptions) (result *v1alpha1.VolumeBackupDelete, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(volumebackupdeletesResource, c.ns, volumeBackupDelete), &v1alpha1.VolumeBackupDelete{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeBackupDelete), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVolumeBackupDeletes) UpdateStatus(ctx context.Context, volumeBackupDelete *v1alpha1.VolumeBackupDelete, opts v1.UpdateOptions) (*v1alpha1.VolumeBackupDelete, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(volumebackupdeletesResource, "status", c.ns, volumeBackupDelete), &v1alpha1.VolumeBackupDelete{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeBackupDelete), err
}

// Delete takes name of the volumeBackupDelete and deletes it. Returns an error if one occurs.
func (c *FakeVolumeBackupDeletes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(volumebackupdeletesResource, c.ns, name, opts), &v1alpha1.VolumeBackupDelete{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumeBackupDeletes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(volumebackupdeletesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VolumeBackupDeleteList{})
	return err
}

// Patch applies the patch and returns the patched volumeBackupDelete.
func (c *FakeVolumeBackupDeletes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VolumeBackupDelete, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(volumebackupdeletesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VolumeBackupDelete{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeBackupDelete), err
}
