---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: kdmp-operator
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - configmaps
      - events
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - kdmp.portworx.com
    resources:
      - dataexports
    verbs:
      - '*'
  - apiGroups:
      - volumesnapshot.external-storage.k8s.io
    resources:
      - volumesnapshotdatas
      - volumesnapshots
    verbs:
      - '*'
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotclasses
      - volumesnapshotcontents
      - volumesnapshots
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kdmp-operator
subjects:
- kind: ServiceAccount
  name: kdmp-operator
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kdmp-operator
  apiGroup: rbac.authorization.k8s.io
