/*

LICENSE

*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BackupLocationMaintenanceLister helps list BackupLocationMaintenances.
// All objects returned here must be treated as read-only.
type BackupLocationMaintenanceLister interface {
	// List lists all BackupLocationMaintenances in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.BackupLocationMaintenance, err error)
	// BackupLocationMaintenances returns an object that can list and get BackupLocationMaintenances.
	BackupLocationMaintenances(namespace string) BackupLocationMaintenanceNamespaceLister
	BackupLocationMaintenanceListerExpansion
}

// backupLocationMaintenanceLister implements the BackupLocationMaintenanceLister interface.
type backupLocationMaintenanceLister struct {
	indexer cache.Indexer
}

// NewBackupLocationMaintenanceLister returns a new BackupLocationMaintenanceLister.
func NewBackupLocationMaintenanceLister(indexer cache.Indexer) BackupLocationMaintenanceLister {
	return &backupLocationMaintenanceLister{indexer: indexer}
}

// List lists all BackupLocationMaintenances in the indexer.
func (s *backupLocationMaintenanceLister) List(selector labels.Selector) (ret []*v1alpha1.BackupLocationMaintenance, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BackupLocationMaintenance))
	})
	return ret, err
}

// BackupLocationMaintenances returns an object that can list and get BackupLocationMaintenances.
func (s *backupLocationMaintenanceLister) BackupLocationMaintenances(namespace string) BackupLocationMaintenanceNamespaceLister {
	return backupLocationMaintenanceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BackupLocationMaintenanceNamespaceLister helps list and get BackupLocationMaintenances.
// All objects returned here must be treated as read-only.
type BackupLocationMaintenanceNamespaceLister interface {
	// List lists all BackupLocationMaintenances in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.BackupLocationMaintenance, err error)
	// Get retrieves the BackupLocationMaintenance from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.BackupLocationMaintenance, error)
	BackupLocationMaintenanceNamespaceListerExpansion
}

// backupLocationMaintenanceNamespaceLister implements the BackupLocationMaintenanceNamespaceLister
// interface.
type backupLocationMaintenanceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BackupLocationMaintenances in the indexer for a given namespace.
func (s backupLocationMaintenanceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.BackupLocationMaintenance, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BackupLocationMaintenance))
	})
	return ret, err
}

// Get retrieves the BackupLocationMaintenance from the indexer for a given namespace and name.
func (s backupLocationMaintenanceNamespaceLister) Get(name string) (*v1alpha1.BackupLocationMaintenance, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("backuplocationmaintenance"), name)
	}
	return obj.(*v1alpha1.BackupLocationMaintenance), nil
}
