/*

LICENSE

*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BackupLocationMaintenanceListerExpansion allows custom methods to be added to
// BackupLocationMaintenanceLister.
type BackupLocationMaintenanceListerExpansion interface{}

// BackupLocationMaintenanceNamespaceListerExpansion allows custom methods to be added to
// BackupLocationMaintenanceNamespaceLister.
type BackupLocationMaintenanceNamespaceListerExpansion interface{}

// DataExportListerExpansion allows custom methods to be added to
// DataExportLister.
type DataExportListerExpansion interface{}

// DataExportNamespaceListerExpansion allows custom methods to be added to
// DataExportNamespaceLister.
type DataExportNamespaceListerExpansion interface{}

// VolumeBackupListerExpansion allows custom methods to be added to
// VolumeBackupLister.
type VolumeBackupListerExpansion interface{}

// VolumeBackupNamespaceListerExpansion allows custom methods to be added to
// VolumeBackupNamespaceLister.
type VolumeBackupNamespaceListerExpansion interface{}
