/*

LICENSE

*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ResourceExportLister helps list ResourceExports.
// All objects returned here must be treated as read-only.
type ResourceExportLister interface {
	// List lists all ResourceExports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ResourceExport, err error)
	// ResourceExports returns an object that can list and get ResourceExports.
	ResourceExports(namespace string) ResourceExportNamespaceLister
	ResourceExportListerExpansion
}

// resourceExportLister implements the ResourceExportLister interface.
type resourceExportLister struct {
	indexer cache.Indexer
}

// NewResourceExportLister returns a new ResourceExportLister.
func NewResourceExportLister(indexer cache.Indexer) ResourceExportLister {
	return &resourceExportLister{indexer: indexer}
}

// List lists all ResourceExports in the indexer.
func (s *resourceExportLister) List(selector labels.Selector) (ret []*v1alpha1.ResourceExport, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ResourceExport))
	})
	return ret, err
}

// ResourceExports returns an object that can list and get ResourceExports.
func (s *resourceExportLister) ResourceExports(namespace string) ResourceExportNamespaceLister {
	return resourceExportNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ResourceExportNamespaceLister helps list and get ResourceExports.
// All objects returned here must be treated as read-only.
type ResourceExportNamespaceLister interface {
	// List lists all ResourceExports in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ResourceExport, err error)
	// Get retrieves the ResourceExport from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ResourceExport, error)
	ResourceExportNamespaceListerExpansion
}

// resourceExportNamespaceLister implements the ResourceExportNamespaceLister
// interface.
type resourceExportNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ResourceExports in the indexer for a given namespace.
func (s resourceExportNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ResourceExport, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ResourceExport))
	})
	return ret, err
}

// Get retrieves the ResourceExport from the indexer for a given namespace and name.
func (s resourceExportNamespaceLister) Get(name string) (*v1alpha1.ResourceExport, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("resourceexport"), name)
	}
	return obj.(*v1alpha1.ResourceExport), nil
}
